[project]
name = "ampliphi"
version = "1.0.4"
description = "A compiler for Ampliphi with target Varphi."
readme = "README.md"
authors = [
    { name = "Hassan El-Sheikha", email = "hassan.elsheikha@utoronto.ca" },
    { name = "Kevin Thevara", email = "kevin.thevara@mail.utoronto.ca" },
    { name = "Youssef Abouzied", email = "youssef.abouzied@mail.utoronto.ca" }
]
requires-python = ">=3.10"
dependencies = [
    "questionary",
    "rich",
    "typer",
    "vp2py>=4.0.0",
]

[project.scripts]
ampliphi = "ampliphi.main:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
