from ..ir import *
from collections import defaultdict

def is_temp(name: str, program: IRProgram) -> bool:
    """Only track variables generated by the compiler's temp counter."""
    return program.variables[name] == IRType.TEMPORARY

def get_used_variables(instruction: IRInstr, program: IRProgram) -> set[str]:
    """Returns a set containing the variables used by a particular instruction (not including assigned variables)"""
    used_variables = set()
    
    match instruction:
        case IRCopy(src=s): 
            used_variables.add(s)
        case IRBinOp(left=l, right=r): 
            used_variables.update({l, r})
        case IRUnOp(operand=o): 
            used_variables.add(o)
        case IRArrayLoad(index=i): 
            used_variables.add(i)
        case IRArrayStore(index=i, value=v): 
            used_variables.update({i, v})
        case IRJumpIfFalse(cond=c): 
            used_variables.add(c)
        case IRHalt():
            # To keep real (non-temporary) variables alive at the end of the program for value observation, we make HALT use all such variables
            for name in program.variables:
                if program.variables[name] != IRType.TEMPORARY and name not in program.arrays:
                    used_variables.add(name)
    return used_variables

def get_defined_variable(instruction: IRInstr, program: IRProgram) -> str | None:
    """Return, if it exists, the name of the variable defined by an instruction."""
    defined_temp = None
    match instruction:
        case IRLoadInt(dest=d) | IRLoadBool(dest=d): 
            defined_temp = d
        case IRCopy(dest=d):
            defined_temp = d            
        case IRBinOp(dest=d):
            defined_temp = d
        case IRUnOp(dest=d):
            defined_temp = d
        case IRArrayLoad(dest=d): 
            defined_temp = d
    return defined_temp
    

def evaluate_binop(op: BinOp, l: int | bool, r: int | bool) -> int | bool:
    """Evaluates a binary operation on two constant values."""
    match op:
        case BinOp.ADD: return l + r
        case BinOp.SUB: return max(0, int(l) - int(r)) # Clamp to 0
        case BinOp.GT:  return l > r
        case BinOp.LT:  return l < r
        case BinOp.EQ:  return l == r
        case BinOp.AND: return l and r
        case BinOp.OR:  return l or r

def evaluate_unop(op: UnOp, val: int | bool) -> int | bool:
    """Evaluates a unary operation on a constant value."""
    match op:
        case UnOp.NOT: return not val

def get_successors(program: IRProgram, instruction_index: int, label_map: dict[str, int]) -> list[int]:
    """
    Determine which instructions can run immediately after this one.
    `label_map` maps label names to the index of the label instruction in the program
    """
    instruction = program.instructions[instruction_index]
    match instruction:
        case IRJump(target=t):
            return [label_map[t]]  # The label instruction can run immediately after
        case IRJumpIfFalse(target=t):
            # The label that we might jump to, or the next instruction, are both successors
            return [label_map[t], instruction_index + 1] if instruction_index < len(program.instructions) - 1 else [label_map[t]]
        case IRHalt():
            return []  # Nothing runs after a HALT
        case _:
            # Any other instruction just has the next instruction as its successor
            return [instruction_index + 1] if instruction_index < len(program.instructions) - 1 else []

def compute_liveness(program: IRProgram) -> tuple[list[set[str]], list[set[str]]]:
        """
        Returns the IN and OUT sets for every instruction
        The IN set tells us which variables are alive just before the instruction executes
        The OUT set tells us which variables are alive just after the instruction executes
        """
        number_of_instructions = len(program.instructions)
        in_sets: list[set[str]] = [set() for _ in range(number_of_instructions)]  # The set of temporaries that are alive just before an instruction executes
        out_sets: list[set[str]] = [set() for _ in range(number_of_instructions)]  # The set of temporaries that are alive just after an instruction executes

        label_map: dict[str, int] = {}  # Maps labels to instruction numbers
        for i, instruction in enumerate(program.instructions):
            if isinstance(instruction, IRLabel):
                label_map[instruction.name] = i
        
        changed = True
        while changed:  # We'll keep iterating until we converge (no sets change)
            changed = False
            # From https://www.youtube.com/watch?v=eeXk_ec1n6g: Iterate bottom-up to converge faster
            for i in range(number_of_instructions - 1, -1, -1):
                instruction = program.instructions[i]
                used_variables = get_used_variables(instruction, program)  # These are the variables used by this instruction
                defined_variable = get_defined_variable(instruction, program)  # This is the variable (if any) defined by this instruction
                
                # OUT[i] = Union of IN[s] for all successors. That is, if a variable is needed at the start of any successor instruction, it must be alive at the end of this instruction (we'll remove variables that we redefine in this instruction later)
                out_sets[i] = set()
                for successor_instruction_index in get_successors(program, i, label_map):
                    out_sets[i].update(in_sets[successor_instruction_index])
                
                
                # IN[i] = USE[i] U (OUT[i] - DEF[i]). That is, a variable is alive before this instruction if this instruction uses it, or if a successor function uses it and we didn't just overwrite it here
                new_in = used_variables | (out_sets[i] - {defined_variable})
                
                if new_in != in_sets[i]:  # Check if the IN-set changed
                    in_sets[i] = new_in
                    changed = True
                    
        return in_sets, out_sets

def create_interference_graph(in_sets: list[set[str]], out_sets: list[set[str]], program: IRProgram) -> dict[str, set[str]]:
    """Return a graph mapping each variable name with the variable names that exist at the same time as it."""
    # 3 rules:
    #   * Two variables in the same IN set cannot share a name
    #   * For a given instruction, the defined variable cannot share the same name as any used variable, since then they'll be forced to share the same tape
    #   * For a given instruction, the defined variable cannot share the same name as a variable in the OUT set, since then we'll be overwriting that variable with a new value accidently even though it's still needed
    interference_graph: dict[str, set[str]] = defaultdict(set)  # Maps vertices (variable names) to their neighbors (two neighbboring variables cannot share the same name)
    for i, instruction in enumerate(program.instructions):
        # First make sure two variables in the same IN set cannot share a name
        in_list = list(in_sets[i])
        for idx1 in range(len(in_list)):
            for idx2 in range(len(in_list)):
                variable1, variable2 = in_list[idx1], in_list[idx2]
                interference_graph[variable1].add(variable2)
                interference_graph[variable2].add(variable1)
        
        defined_variable = get_defined_variable(instruction, program)
        if defined_variable:
            # Next make sure that the defined variable cannot share a name with the used variables and vice versa
            used_variables = get_used_variables(instruction, program)
            for used_variable in used_variables:
                interference_graph[defined_variable].add(used_variable)
                interference_graph[used_variable].add(defined_variable)
            
            # Finally, make sure that the defined variable cannot share a name with variables in the OUT set, and vice versa
            for variable in out_sets[i]:
                interference_graph[defined_variable].add(variable)
                interference_graph[variable].add(defined_variable)
    return interference_graph


def get_variable_to_color(interference_graph: dict[str, set[str]]) -> dict[str, int]:
    """Color a given interference graph to determine the optimized new names of variables."""
    # Greedy coloring
    variable_to_color: dict[str, int] = {}  # This will map variable names to their new variable name
    
    # Sort by most interferences first (heuristically better coloring)
    variables = sorted(interference_graph.keys(), key=lambda t: len(interference_graph[t]), reverse=True)
    
    for variable in variables:
        invalid_colors = set()
        for neighbor in interference_graph[variable]:
            if neighbor in variable_to_color:  # i.e., the neighbor has already been given a new name
                invalid_colors.add(variable_to_color[neighbor]) # These two cannot share the same name
        # Find the lowest color that we can give to this variable without causing a conflict
        color = 0
        while color in invalid_colors:
            color += 1     
        variable_to_color[variable] = color
    return variable_to_color
